name: Reiter Application Minimal demo

apps:
  /:
    factory: ${dotted:reiter.application.app.BrowserApplication}
    config:
      routes: ${dotted:reiter_minimal.routes}

server:
  factory: ${dotted:bjoern.run}
  config:
    host: 0.0.0.0
    port: 8080
    reuse_port: true
